version: '3.6'

services:
  api:
    build: .
    image: simple
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["./wait-for-it.sh","db:3306", "--","./simple"]
  db:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
   